### ISSUE TITLE
Having issues with autoscaling.

### ISSUE THREAD

**Issue by ghost** [MonsantoCo/etcd-aws-cluster#24] opened 2016-06-03 18:58 UTC
Issue I'm running into:

Steps:
Start a new cluster with 3 nodes...  Etcd comes up okay.  

Autoscale to 6 nodes..

Etcd fails on new nodes:
Jun 03 18:38:03 ip-10-7-2-18.ec2.internal docker[5987]: 2016/06/3 18:38:03 etcdmain: error validating peerURLs {ClusterID:8a188635e6676cf7 Members:[&{ID:5db898d9b2673eb3 RaftAttributes:{PeerURLs:[http://10.7.2.18:2380]} Attributes:{Name: ClientURLs:[]}} &{ID:610c3a0ab98d72b7 RaftAttributes:{PeerURLs:[http://10.7.1.167:2380]} Attributes:{Name:i-fcdc0904 ClientURLs:[http://10.7.1.167:2379]}} &{ID:80c9803aa2fa7908 RaftAttributes:{PeerURLs:[http://10.7.2.17:2380]} Attributes:{Name: ClientURLs:[]}} &{ID:e23dd231e95a85b4 RaftAttributes:{PeerURLs:[http://10.7.1.205:2380]} Attributes:{Name: ClientURLs:[]}} &{ID:e8071ff486efa6f2 RaftAttributes:{PeerURLs:[http://10.7.1.166:2380]} Attributes:{Name:i-fbdc0903 ClientURLs:[http://10.7.1.166:2379]}} &{ID:fe69d87bb0fad3a0 RaftAttributes:{PeerURLs:[http://10.7.2.16:2380]} Attributes:{Name:i-96589a10 ClientURLs:[http://10.7.2.16:2379]}}] RemovedMemberIDs:[]}: member count is unequal

Here is the generated file:
cat /etc/sysconfig/etcd-peers

```
ETCD_INITIAL_CLUSTER_STATE=existing
ETCD_NAME=i-32ac62b4
ETCD_INITIAL_CLUSTER="i-fcdc0904=http://10.7.1.167:2380,=http://10.7.1.205:2380,i-fbdc0903=http://10.7.1.166:2380,i-96589a10=http://10.7.2.16:2380,i-32ac62b4=http://10.7.2.18:2380"
```

I suspect it's the missing ID above in the initial cluster list which is breaking things.  

Any help would be appreciated!

**Comment by tjcorr** [comment] 2016-06-03 19:40
I just ran the test you described and ran into a similar problem. I'm thinking the problem is coming from trying to add multiple nodes at nearly the exact same time. Especially since you are basically breaking quorum by doubling the number of nodes. If you go up one node at a time and wait for things to stabilize before adding the next everything should work just fine. I'll try and play around a bit and see if we can't make this a bit more robust on our end though.

**Comment by insidewhy** [comment] 2016-07-21 11:33
See a similar thing here... raised from 3 hosts to 15. We see that most machines don't have `/etc/sysconfig/etcd-peers`. We see one with a `,=http://...` entry, and a bunch that disagree.

Scaling up one instance at a time is no good for us, our traffic is super spikey.

**Comment by insidewhy** [comment] 2016-07-21 11:36
Anyone here find a system that actually works to keep their aws etcd cluster in sync?

**Comment by tomfotherby** [comment] 2016-07-21 11:53
@ohjames - You could separate your etcd cluster from your app server cluster so you can quickly scale up/down your app without needing to change your etcd cluster and risk sync issues. Check this documentation exploring workers vs etcd clusters: https://coreos.com/os/docs/latest/cluster-architectures.html

**Comment by tjcorr** [comment] 2016-07-21 12:29
I'll echo @tomfotherby and suggest that you probably shouldn't be autoscaling your etcd masters. 

Rapidly adding machines is unlikely to ever truly work due to how consensus is maintained in etcd. For etcd to work properly quorum must always be maintained. If you start with 3 machines and then add 3 more you have essentially created a split brain system where you have only 3/6 nodes actively participating. Technically you should be able to add 2 more on top of 3 but then you have created a system that temporarily has no fault tolerance.  See https://coreos.com/etcd/docs/latest/admin_guide.html#optimal-cluster-size for more details. The safest thing to do is always just add 1 at a time and wait for all the data to replicate across and the cluster to stabilize before adding additional nodes. 

I'll also note that running a large number of etcd masters actually slows down the system as the overhead to keep everything in sync and enforce consistency on writes grows with the number of nodes. I normally suggest that most people go for 5 etcd masters spread across 3 availability zones (2/2/1). This ensures any single AZ failure keeps you with quorum. Unless you are doing a crazy number of read/writes you likely won't need any additional machines running etcd.

Their are 2 alternative approaches that I would suggest instead for autoscaling:
1. Autoscale the etcd proxy autoscaling group in the example cloud formation. These machines still have etcd on them, they just proxy request to the etcd masters (see https://coreos.com/etcd/docs/latest/proxy.html) . This should work pretty seamlessly since every machine will still behave just like it has etcd on it itself. 
2. Autoscale a separate autoscaling group that doesn't run etcd at all. Instead you can create an ELB that sits in front of the etcd masters and possibly give it a nice route 53 entry. Then on these machines when they need to reference etcd they can just list the ELB. For example in fleet you would just do:
   
   ```
   fleet:
   public-ip: $%advertisedIp%_ipv4
   etcd-servers: "http://etcd.internal" 
   ```
   
   Applications using etcd could also just use the ELB as well. This is the approach we are using internally.

Hope that helps, let me know if you have any other questions.

https://coreos.com/os/docs/latest/cluster-architectures.html#production-cluster-with-central-services

**Comment by tjcorr** [comment] 2016-07-21 16:43
I'm going to close this one out as something we can't really support. This was mostly designed to maintain an etcd cluster not scale. If anyone has ideas of better ways to improve though we're certainly open to merging it in.

**Closed as completed by tjcorr** 2016-07-21 16:43 UTC

**Comment by insidewhy** [comment] 2016-07-25 16:18
Thanks for your help!

I went with two auto-scaling groups, one for etcd peers and then another for etcd proxies. The etcd proxy auto-scaling group uses a simpler version of the aws-etcd-cluster container to find the proxies based on instance tags.

**Comment by akanshajain1** [comment] 2017-07-20 19:05
Hi I tried this with adding only one node to etcd cluster but its showing error validating peerURLs infra0=http://10.31.166.6:2380,infra1=http://10.31.104.13:2380 :: member count is unequal
But in another two nodes ip of new added instance is showing as Listen_Client_Urls
